### ISSUE TITLE
emerge: there are no ebuilds to satisfy ">=net-libs/kdav2-0.3".

### ISSUE THREAD

**Issue by Albert753258** [pinetoo/pinetoo#3]
emerge --ask plasma-mobile-meta --keep-going --jobs 4

 * IMPORTANT: 13 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.

These are the packages that would be merged, in order:

Calculating dependencies... done!
Dependency resolution took 97.30 s (backtrack: 3/20).

emerge: there are no ebuilds to satisfy ">=net-libs/kdav2-0.3".
(dependency required by "dev-libs/sink-0.9.0::pinetoo" [ebuild])
(dependency required by "kde-misc/kpeoplesink-20220707::pinetoo" [ebuild])
(dependency required by "kde-plasma/plasma-mobile-meta-5.27.9::pinetoo" [ebuild])
(dependency required by "plasma-mobile-meta" [argument])

**Comment by Albert753258** [comment]
It was removed in https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=601e9b1b4c436c61e9c3a91215274c8782fb2d11

**Comment by chusopr** [comment]
Hi, sorry, this repo didn't get a lot of updates lately, but it's still active, I've just been busy trying to add an ebuild for [FluffyChat](https://fluffychat.im/), but it depends on Dart and Flutter which are a nightmare to package.

Yes, all packages related to `dev-libs/sink` were recently removed form `::gentoo` because it seems like upstream has abandoned and it currently doesn't build as you already noticed in #5.

I will follow the same move and remove everything related to `dev-libs/sink`. So far, I've been trying to make it build by patching it and pulling old dependencies, but there is no point in doing such dirty patches to try to build something that has been abandoned upstream.
